/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#fff8f6',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#feede7',
        'inverse-primary': '#ffb694',
        'inverse-surface': '#382e2a',
        'on-background': '#221a16',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-container': '#77320b',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#77320b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#0d706f',
        'on-secondary-fixed': '#002020',
        'on-secondary-fixed-variant': '#00504f',
        'on-surface': '#221a16',
        'on-surface-variant': '#54433b',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#444749',
        'on-tertiary-fixed': '#191c1d',
        'on-tertiary-fixed-variant': '#444748',
        outline: '#87736a',
        'outline-variant': '#dac1b7',
        primary: '#954921',
        'primary-container': '#ff9d6e',
        'primary-fixed': '#ffdbcc',
        'primary-fixed-dim': '#ffb694',
        secondary: '#006a69',
        'secondary-container': '#9ff1ef',
        'secondary-fixed': '#9ff1ef',
        'secondary-fixed-dim': '#83d4d3',
        surface: '#fff8f6',
        'surface-bright': '#fff8f6',
        'surface-container': '#fbeae4',
        'surface-container-high': '#f5e5df',
        'surface-container-highest': '#efdfd9',
        'surface-container-low': '#fff1ec',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#e7d7d1',
        'surface-tint': '#954921',
        'surface-variant': '#efdfd9',
        tertiary: '#5c5f60',
        'tertiary-container': '#b3b6b7',
        'tertiary-fixed': '#e1e3e4',
        'tertiary-fixed-dim': '#c4c7c8'
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        'level-1': '0 8px 30px rgba(0,0,0,0.04)',
        'level-2': '0 12px 40px rgba(0,0,0,0.08)',
        'level-3': '0 16px 50px rgba(149,73,33,0.12)'
      }
    },
  },
  plugins: [],
}
